### ISSUE TITLE
字段名建议用驼峰，不要用下划线。

### ISSUE THREAD

**Issue by longxianlin** [zhblue/crud#1]

**Comment by zhblue** [comment]
因为要通过字段名自动识别和绑定表关联，个人感觉_id比Id的要更加容易识别。
_可以作为字符串处理的标志物，而I(大写i)和l(小写L)是很难区分的。
此外很多数据库默认是不区分大小写的，采用驼峰式命名可能会带来潜在的麻烦。

**Comment by zhblue** [comment]
比如有个表叫to(id,name)，另一个表say里有个外键用to.id，命名为toId，你能肉眼区分told和toId么？

say(id,toId,told)和say(id,to_id,told) 那个更清晰易懂呢？
